//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package ru.nsu.leontev.request;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="RequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="PartNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="PartCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="Alphabet">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="symbols" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "partNumber",
    "partCount",
    "hash",
    "maxLength",
    "alphabet"
})
@XmlRootElement(name = "CrackHashManagerRequest")
public class CrackHashManagerRequest {

    /**
     * GUID запроса
     * 
     */
    @XmlElement(name = "RequestId", required = true)
    protected String requestId;
    /**
     * Номер части запроса
     * 
     */
    @XmlElement(name = "PartNumber")
    protected int partNumber;
    /**
     * Общее количество частей
     * 
     */
    @XmlElement(name = "PartCount")
    protected int partCount;
    /**
     * Хэш
     * 
     */
    @XmlElement(name = "Hash", required = true)
    protected String hash;
    /**
     * Максимальная длина последовательности
     * 
     */
    @XmlElement(name = "MaxLength")
    protected int maxLength;
    /**
     * Алфавит для генерации строк
     * 
     */
    @XmlElement(name = "Alphabet", required = true)
    protected CrackHashManagerRequest.Alphabet alphabet;

    /**
     * GUID запроса
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRequestId()
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Номер части запроса
     * 
     */
    public int getPartNumber() {
        return partNumber;
    }

    /**
     * Sets the value of the partNumber property.
     * 
     */
    public void setPartNumber(int value) {
        this.partNumber = value;
    }

    /**
     * Общее количество частей
     * 
     */
    public int getPartCount() {
        return partCount;
    }

    /**
     * Sets the value of the partCount property.
     * 
     */
    public void setPartCount(int value) {
        this.partCount = value;
    }

    /**
     * Хэш
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getHash()
     */
    public void setHash(String value) {
        this.hash = value;
    }

    /**
     * Максимальная длина последовательности
     * 
     */
    public int getMaxLength() {
        return maxLength;
    }

    /**
     * Sets the value of the maxLength property.
     * 
     */
    public void setMaxLength(int value) {
        this.maxLength = value;
    }

    /**
     * Алфавит для генерации строк
     * 
     * @return
     *     possible object is
     *     {@link CrackHashManagerRequest.Alphabet }
     *     
     */
    public CrackHashManagerRequest.Alphabet getAlphabet() {
        return alphabet;
    }

    /**
     * Sets the value of the alphabet property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrackHashManagerRequest.Alphabet }
     *     
     * @see #getAlphabet()
     */
    public void setAlphabet(CrackHashManagerRequest.Alphabet value) {
        this.alphabet = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="symbols" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "symbols"
    })
    public static class Alphabet {

        protected List<String> symbols;

        /**
         * Gets the value of the symbols property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the symbols property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getSymbols().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * </p>
         * 
         * 
         * @return
         *     The value of the symbols property.
         */
        public List<String> getSymbols() {
            if (symbols == null) {
                symbols = new ArrayList<>();
            }
            return this.symbols;
        }

    }

}
