//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package ru.nsu.leontev.response;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="RequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="PartNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="combChecked" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="Answers">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="words" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "partNumber",
    "combChecked",
    "answers"
})
@XmlRootElement(name = "CrackHashWorkerResponse")
public class CrackHashWorkerResponse {

    /**
     * GUID запроса
     * 
     */
    @XmlElement(name = "RequestId", required = true)
    protected String requestId;
    /**
     * Номер запроса
     * 
     */
    @XmlElement(name = "PartNumber")
    protected int partNumber;
    /**
     * Количество проверенных комбинаций
     * 
     */
    protected long combChecked;
    /**
     * Строки
     * 
     */
    @XmlElement(name = "Answers", required = true)
    protected CrackHashWorkerResponse.Answers answers;

    /**
     * GUID запроса
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRequestId()
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Номер запроса
     * 
     */
    public int getPartNumber() {
        return partNumber;
    }

    /**
     * Sets the value of the partNumber property.
     * 
     */
    public void setPartNumber(int value) {
        this.partNumber = value;
    }

    /**
     * Количество проверенных комбинаций
     * 
     */
    public long getCombChecked() {
        return combChecked;
    }

    /**
     * Sets the value of the combChecked property.
     * 
     */
    public void setCombChecked(long value) {
        this.combChecked = value;
    }

    /**
     * Строки
     * 
     * @return
     *     possible object is
     *     {@link CrackHashWorkerResponse.Answers }
     *     
     */
    public CrackHashWorkerResponse.Answers getAnswers() {
        return answers;
    }

    /**
     * Sets the value of the answers property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrackHashWorkerResponse.Answers }
     *     
     * @see #getAnswers()
     */
    public void setAnswers(CrackHashWorkerResponse.Answers value) {
        this.answers = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="words" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "words"
    })
    public static class Answers {

        protected List<String> words;

        /**
         * Gets the value of the words property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the words property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getWords().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * </p>
         * 
         * 
         * @return
         *     The value of the words property.
         */
        public List<String> getWords() {
            if (words == null) {
                words = new ArrayList<>();
            }
            return this.words;
        }

    }

}
